name: Deploy to Production Server

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.PROD_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ vars.PROD_SERVER_HOST }} >> ~/.ssh/known_hosts
          echo "Host ${{ vars.PROD_SERVER_HOST }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          cat ~/.ssh/config

      - name: Deploy to Production Server
        env:
          PROD_SERVER_HOST: ${{ vars.PROD_SERVER_HOST }}
          PROD_SERVER_USER: ${{ vars.PROD_SERVER_USER }}
          PROD_PROJECT_PATH: ${{ vars.PROD_PROJECT_PATH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $PROD_SERVER_USER@$PROD_SERVER_HOST << EOF
          cd $PROD_PROJECT_PATH
          git init
          git remote add origin https://github.com/your-username/your-repo.git
          git fetch origin
          git reset --hard origin/prod
          docker-compose -f deploy-compose.yml up -d
          EOF
