name: Deploy to Production Server

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.PROD_SERVER_HOST }}

      - name: Deploy to Production Server
        env:
          PROD_SERVER_HOST: ${{ secrets.PROD_SERVER_HOST }}
          PROD_SERVER_USER: ${{ secrets.PROD_SERVER_USER }}
          PROD_PROJECT_PATH: ${{ vars.PROD_PROJECT_PATH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no $PROD_SERVER_USER@$PROD_SERVER_HOST << EOF
          cd $PROD_PROJECT_PATH
          git init
          git remote add origin ${{ github.repositoryUrl }}
          git fetch origin
          git reset --hard origin/prod
          docker-compose -f deploy-compose.yml up -d
          EOF
