name: Deploy to Production Server

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.PROD_SERVER_SSH_KEY }}" > ~/.ssh/server_key
          cat ~/.ssh/server_key
          chmod 600 ~/.ssh/server_key

      - name: Deploy to Production Server
        env:
          PROD_SERVER_HOST: ${{ vars.PROD_SERVER_HOST }}
          PROD_SERVER_USER: ${{ vars.PROD_SERVER_USER }}
          PROD_PROJECT_PATH: ${{ vars.PROD_PROJECT_PATH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deploying to production server..."
          echo "$PROD_SERVER_USER@$PROD_SERVER_HOST:$PROD_PROJECT_PATH"
          echo "$(cat ~/.ssh/server_key)"
          export COMMAND="ssh -o StrictHostKeyChecking=no -i ~/.ssh/server_key $PROD_SERVER_USER@$PROD_SERVER_HOST"
          echo $COMMAND
          $COMMAND << EOF
          echo "Connected to production server"
          EOF
